image: node:latest

stages:
  - build
  - deploy

before_script:
  - npm install -g firebase-tools

build:
  stage: build
  script:
    - npm install
    - npm run build

deploy:
  stage: deploy
  script:
    - firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
  only:
    - master
